services:
  db:
    image: postgres:16
    container_name: pharmacy_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: pharmacy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d pharmacy"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: